name: Scrape latest data

on:
  push:
  workflow_dispatch:
  # schedule:
  #    - cron:  '1 0/4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: restart docker with smaller MTU
      run: |-
        temp=$(mktemp)
        jq '. + {"mtu": 1280 }'  < "/etc/docker/daemon.json" > "$temp"
        sudo mv "$temp" "/etc/docker/daemon.json"
        sudo  systemctl restart docker
        echo "restarted"
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: Fetch latest data
      env:
        FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        LIFELINE_CONNECTION_STRING: ${{ secrets.LIFELINE_CONNECTION_STRING }}
      run: |-
        ./runGarminDb.sh --all --download --import --analyze
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dbs-and-log
        path: |
          DBs
          *.log
