name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |-
        ./run.sh
