name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Fetch latest data
      env:
        FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        SSHPASS: ${{secrets.SSHPASS }}
      run: |-
        sshpass ssh -D 8080 pi@raspberrypi
        ./run.sh
