name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Docker build
      run: |-
        ./run.sh --only-build
    - name: Tailscale
      uses: tailscale/github-action@main
      with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: " --exit-node=100.97.181.28 --exit-node-allow-lan-access=true"
    - name: curl
      run: |-
        docker pull curlimages/curl:7.81.0
        temp=$(mktemp)
        jq '. + {"mtu": 1280 }'  < "/etc/docker/daemon.json" > "$temp"
        sudo mv "$temp" "/etc/docker/daemon.json"
        cat "/etc/docker/daemon.json"
        sudo  systemctl restart docker
        echo "restarted"
        docker run --rm curlimages/curl:7.81.0 -L -vvvv https://tailscale.com 
        echo "outside curl:"
        curl:7.81.0 -L -vvvv https://tailscale.com 

    - name: Fetch latest data
      env:
        FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |-
        ./run.sh
