name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Docker build
      run: |-
        ./run.sh --only-build  
        ip route show
    - name: Tailscale
      uses: tailscale/github-action@main
      with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: " --exit-node=100.97.181.28 --tun=userspace-networking"
    - name: curl
      run: |-
        ip route show
        echo "outside works ^, now inside docker:"
        docker network create --subnet 172.20.0.0/24 wgnet
        ip route show
        echo "ip rpute:"
        docker pull curlimages/curl:7.81.0
        docker run --network wgnet --device /dev/net/tun --cap-add=NET_ADMIN --rm curlimages/curl:7.81.0 -L -vvvv https://tailscale.com & 
        sleep 10
        ip route show
        wait 

    - name: Fetch latest data
      env:
        FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |-
        ./run.sh
