name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
   - cron:  '1 0/8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: restart docker with smaller MTU
      run: |-
        temp=$(mktemp)
        sudo touch "/etc/docker/daemon.json"
        jq '. + {"mtu": 1280 }'  < "/etc/docker/daemon.json" > "$temp"
        sudo mv "$temp" "/etc/docker/daemon.json"
        sudo  systemctl restart docker
        echo "restarted"
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        args: --accept-dns=false
    - name: Fetch latest data
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |-
        git config --global pack.window 1 # https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet
        git config --global core.compression 0
        ./runGarminDb.sh --activities --weight --sleep --rhr --monitoring --import --analyze --latest
      # Statistics:
      #   -A, --all             Download and/or import data for all enabled stats.
      #   -a, --activities      Download and/or import activities data.
      #   -m, --monitoring      Download and/or import monitoring data.
      #   -r, --rhr             Download and/or import resting heart rate data.
      #   -s, --sleep           Download and/or import sleep data.
      #   -w, --weight          Download and/or import weight data.
      #
      # Modifiers:
      #     -l, --latest          Only download and/or import the latest data.
      #     -o, --overwrite       Overwite existing files when downloading. The default
      #       is to only download missing files.
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dbs-and-log
        path: |
          DBs
          *.log
